name: SuperKart CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyngrok
        pip install datasets

    - name: Run data preparation
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python scripts/prep.py

    - name: Train model
      run: python scripts/train.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: xgb-model
        path: xgb_model.pkl

    - name: Deploy Streamlit app with ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      run: |
        ngrok config add-authtoken $NGROK_TOKEN
        nohup streamlit run hosting/hosting.py --server.port=8501 &
        sleep 10
        ngrok http 8501 > ngrok_url.txt &
        sleep 10
        cat ngrok_url.txt
